# Generated by Django 5.1.3 on 2024-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chef",
            name="years_of_experience",
            field=models.IntegerField(default=1),
        ),
    ]
