# Generated by Django 5.1.3 on 2024-12-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ("name",)},
        ),
        migrations.DeleteModel(
            name="Chef",
        ),
    ]
