# Generated by Django 5.1.3 on 2024-12-03 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_remove_dish_chefs_dish_chefs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="chefs",
            field=models.ManyToManyField(
                related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
